### ISSUE TITLE
[BUG] ping message isn't filtered by Channel Id (mattermost)

### ISSUE THREAD

**Issue by daegeun-ha** [infracloudio/botkube#205]
**Describe the bug**
ping message isn't filtered by channel id.

**To Reproduce**
1. Make two different channels in same mattermost team.
2. Figure one channel to botkube pod. (botkube pod only knows one channel)
3. Send 'ping' message from two different channels.
4. You can see 'pong' message in both channels!

**Expected behavior**
Only one figured pod that is figured in botkube pod can receive 'pong' message

**Screenshots**

**Additional context**

**Comment by PrasadG193** [comment]
@daegeun-ha By design `ping` and `kubectl` commands are expected to run anywhere. To execute kubectl commands outside of configured channel, you have to pass `--cluster-name` flag. `ping` command can run without `--cluster-name` flag. Please execute `/botkubehelp` if you have configured Slash command in Mattermost

**Comment by daegeun-ha** [comment]
I checked it. Thanks :)
