### ISSUE TITLE
[Slack] is it necessary for BotKube to require permissions to view messages and files across all channels

### ISSUE THREAD

**Issue by shubhamoli** [infracloudio/botkube#246]
Hey Team,

I really liked the product and was looking for something similar for few days and found Botkube really amazing. I truly want to give it a try with our Slack Workspace but:

I've one concern... during installation Botkube requires permission to view messages and files across all channels. Is it compulsory or something minimal than this could've been fine?

**Comment by sanketsudake** [comment]
Hey @shubhamoli,

We require access to Slack channels so that we can respond to kubectl commands posted by users. As of now default app in Slack directory requires these permissions. I assume you can do the personal installation and modify permissions.
However, as you know both BotKube Slack and backend are hosted by user itself. So we don't gather any info.

Please let us know if you have any specific concerns considering the above details/

**Comment by shubhamoli** [comment]
> However, as you know both BotKube Slack and backend are hosted by user itself. So we don't gather any info.

Yeah, it makes sense, I ignored this completely. Thanks for the clarification @sanketsudake 

Integrating Botkube today. Thank you guys for making this awesome product
