### ISSUE TITLE
[BUG] kubectl commands slow response with message "Waited for <x>s due to client-side throttling, not priority and fairness"

### ISSUE THREAD

**Issue by prashant2402** [infracloudio/botkube#564]
**Describe the bug**
Kubectl commands output takes long time before showing the output. See this message with the output: 

```
Cluster: xxxx-k8s
I0205 13:10:58.695546      23 request.go:665] Waited for 1.08049639s due to client-side throttling, not priority and fairness, request: GET:[https://x.x.x.x:443/apis/discovery.k8s.io/v1beta1?timeout=32s](https://x.x.x.x/apis/discovery.k8s.io/v1beta1?timeout=32s)
I0205 13:11:09.895395      23 request.go:665] Waited for 1.195560219s due to client-side throttling, not priority and fairness, request: GET:[https://x.x.x.x:443/apis/storage.k8s.io/v1beta1?timeout=32s](https://x.x.x.x/apis/storage.k8s.io/v1beta1?timeout=32s)
I0205 13:11:20.095159      23 request.go:665] Waited for 11.39491933s due to client-side throttling, not priority and fairness, request: GET:[https://x.x.x.x:443/apis/crd.projectcalico.org/v1?timeout=32s](https://x.x.x.x/apis/crd.projectcalico.org/v1?timeout=32s)
NAME                                          READY   STATUS             RESTARTS   AGE
testmodel-default-0-model1-6fbf95df6c-2dfd7   0/2     ImagePullBackOff   0          50m
```
Using the latest v0.12.4 image of botkube.
I am using AKS, server version is
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-18T00:11:23Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
**Screenshots**
![Screenshot 2022-02-05 133023](https://user-images.githubusercontent.com/1729202/152644143-4a37ef68-7bca-40b6-bf1b-d88925c1f78b.png)

**Comment by pkosiec** [comment]
Hi @prashant2402,

While I couldn't reproduce such throttling on my local machine (as it may vary between different cluster configurations, and how many services you have installed, which access Kubernetes API server), I noticed one thing. If I run any command with the highest verbosity level (e.g. `@BotKube get po -v=10`) I can observe the following line in debug logs:

```
I0517 14:08:54.368841      24 cached_discovery.go:87] failed to write cache to /.kube/cache/discovery/10.43.0.1_443/v1/serverresources.json due to mkdir /.kube: read-only file system
```

This might be a reason of such throttling. Because of inability to write cache, BotKube does a big amount of requests to K8s API, and that's why it's being throttled - and that results in slow BotKube responses. 

Same issues were reported in different places, e.g.:
- https://github.com/rancher/rke2/issues/2119
- https://stackoverflow.com/questions/66339069/kubectl-get-all-command-return-throttling-request
- https://stackoverflow.com/questions/71596906/client-side-throttling-response-from-kubernetes-kubectl-command

I will try to take a look on this issue 🙂  Cheers!
