### ISSUE TITLE
MS Teams integration doesn't work with the latest develop

### ISSUE THREAD

**Issue by mszostok** [infracloudio/botkube#606]
**Describe the bug**

MS Teams integration doesn't work with the latest develop (tag: `v9.99.9-dev`)

**To Reproduce**
I follow the [MS Teams Bot Development](https://www.botkube.io/contribute/ms-teams-develop/) tutorial and if I install the BotKube with such command:
```bash
helm install botkube --namespace botkube \
--set communications.teams.enabled=true \
--set communications.teams.appID='dbf68a92-26a0-4305-8e9b-8616500abf2f' \
--set communications.teams.appPassword='K988Q' \
--set config.settings.clustername=ms-team \
--set config.settings.kubectl.enabled=true \
./helm/botkube
```
then everything works well.

However, if I will install it with the newest BotKube image:

```bash
helm install botkube --namespace botkube --set image.tag=v9.99.9-dev \
--set communications.teams.enabled=true \
--set communications.teams.appID='dbf68a92-26a0-4305-8e9b-8616500abf2f' \
--set communications.teams.appPassword='K988Q' \
--set config.settings.clustername=ms-team \
--set config.settings.kubectl.enabled=true \
./helm/botkube
```
then the endpoint returns `404 page not found`
![Screen Shot 2022-06-02 at 12 39 05](https://user-images.githubusercontent.com/17568639/171612176-85370f64-90d8-472b-bc15-efac8c28ce8d.png)

there are also no useful headers in the response:
```
curl -v http://localhost:3978
*   Trying 127.0.0.1:3978...
* Connected to localhost (127.0.0.1) port 3978 (#0)
> GET / HTTP/1.1
> Host: localhost:3978
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 02 Jun 2022 10:43:00 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host localhost left intact
 
```

As you can see the chart itself, it's not a problem. It seems to be related to the code changes.

**Comment by pkosiec** [comment]
The reason is that between develop and the last release there was this little innocent change:
https://github.com/infracloudio/botkube/compare/v0.12.4...develop?expand=1#diff-20eaa0dac853ef588d89b539f6cf4dbec2fd2baaa09959cd7796be63956aa84cR333 
![Screenshot 2022-06-02 at 14 09 34](https://user-images.githubusercontent.com/7155799/171626120-01beffff-20b8-4bb9-bf57-435ce78dc764.png)

Why did it work previously? Simply because MS Teams server were registered on "/":

```go
	msgPath := c.Communications.Teams.MessagePath
	if msgPath == "" {
		msgPath = "/"
	}
```

> Note that since a pattern ending in a slash names a rooted subtree, the pattern "/" matches all paths not matched by other registered patterns, not just the URL with Path == "/". 

https://pkg.go.dev/net/http#NewServeMux 

You can see how it works in `v0.12.4` when you call `http://localhost:3978/` or `http://localhost:3978/anything` :
And in logs, you'll see: `Failed to parse Teams request. Authentication headers are missing in the request`

Why do the old image work with the latest Helm chart? It's because of this change on develop:
https://github.com/infracloudio/botkube/compare/v0.12.4...develop?expand=1#diff-a3d824da3c42420cd5cbb0a4a2c0e7b5bfddd819652788a0596d195dc6e31fa5L195 

![Screenshot 2022-06-02 at 14 10 51](https://user-images.githubusercontent.com/7155799/171626277-5ceb7d10-4337-4de2-96bb-fce373fb7ea9.png)

The property was ignored while loading configuration. 

Because of using default HTTP server both for MS Teams and metrics, the `/metrics` endpoint is also registered on this server: `curl http://localhost:3978/metrics` which is something already fixed in: https://github.com/infracloudio/botkube/pull/603.

To fix this issue, I will use https://github.com/gorilla/mux to handle `PathPrefix` for all the separate servers.
