### ISSUE TITLE
BotKube Commands are not responding in Mattermost channel

### ISSUE THREAD

**Issue by sudhanshu456** [infracloudio/botkube#618]
**Describe the bug**
Changes notifications are coming in Mattermost (for both Mattermost online and open-source version) channel but @botkube ping and other commands are not responding anything.

**To Reproduce**
1. Configure Botkube with Mattermost server.
2. You can see the message saying `...and now my watch begins for cluster 'cluster_name'! :crossed_swords:` if configured successfully.
3. Run `@botkube ping` in the configured channel.
4. You will see it output nothing on the channel. (See Screenshot).

![image](https://user-images.githubusercontent.com/44128982/173762319-771343e5-5ec6-47f2-92da-25901c7403e9.png)

**Expected behavior**
It should output something as mentioned in the docs `Send @BotKube ping in the channel to see if BotKube is running and responding.` [here](https://www.botkube.io/installation/mattermost/#botkube-install-using-helm)
 
**Screenshots**
Ignore the change notification in screenshot.
![image](https://user-images.githubusercontent.com/44128982/173762821-3bcc08ca-de01-4a87-b79f-93d27d230cc2.png)

On running with debug mode.
![image](https://user-images.githubusercontent.com/44128982/173762929-b6026657-d521-456b-8379-4e7650ecc41a.png)

On running `@botkube get pods` in the channel doesn't return anything.
![Screenshot from 2022-06-15 12-31-39](https://user-images.githubusercontent.com/44128982/173763498-c3f6f020-1d89-41f4-bbe9-1ef45a4dab10.png)

**Additional context**
BotKube Version: v0.12.4

**Comment by recrudesce** [comment]
I'm having exactly the same issue - no botkube commands work, but notifications are fine.

**Comment by pkosiec** [comment]
Hi @sudhanshu456  and @recrudesce, it looks like the bot name is improperly configured on your clusters.


For example, on your screenshot @sudhanshu456 I see that the bot name is `botkube`, and I guess when you followed the instruction https://www.botkube.io/installation/mattermost/, in the configuration you provided `BotKube` as  `MATTERMOST_BOT_NAME`. Is that correct? Please try to upgrade/reinstall the Helm chart with the `--set communications.mattermost.botName=botkube` override.

Let me know if that works 🙂

**Comment by sudhanshu456** [comment]
I followed exactly what you said but it didn't work. 
![Screenshot from 2022-06-17 14-53-48](https://user-images.githubusercontent.com/44128982/174269685-f777dd10-67e0-412f-8e78-ba895c1c218d.png)

Did you notice in the above screenshot where I'm getting notifications like the watch is started? @pkosiec

**Comment by pkosiec** [comment]
Okay, but that's a different situation than the first screenshot from the issue. So you have to revert the change I described.

Once you reinstalled BotKube with `communications.mattermost.botName=BotKube` again, please try to type the message, but don't accept autocomplete suggestion when it comes to the user name. Because looks like Mattermost have a bit different behavior when you accept the autocomplete when there are uppercase characters.
So, for example, you can copy and paste the message:

```
@BotKube ping
```

If that works, please let us know. But please double check if the `communications.mattermost.botName` and also bot username is `BotKube` (casing is very important). Thanks!

**Comment by recrudesce** [comment]
Would it not be sensible to just standardise the case of the received name and the value read from the config file ?

That way it doesn't matter if you use @BOTKUBE when the config is @BoTkUbE etc.

Just lowercase it all ?

**Comment by recrudesce** [comment]
> If that works, please let us know. But please double check if the `communications.mattermost.botName` and also bot username is `BotKube` (casing is very important). Thanks!

Interestingly, if you deploy via kubectl instructions (as in you don't use Helm), the documentation at no point tells you to set this in the config, and the provided YAML doesn't have this configuration option present.

**Comment by sudhanshu456** [comment]
Bot Name value can be set in YAML but I'm not sure this information is even present in present docs due to this if you deploy BotKube using kubectl [as mentioned [here](https://www.botkube.io/installation/mattermost/#using-kubectl) ] and you don't specify any bot name and remain empty and BotKube keeps on ignoring incoming messages.

You need to specify the bot name in YAML like this. @recrudesce 
![Screenshot from 2022-06-17 22-29-40](https://user-images.githubusercontent.com/44128982/174344069-b6459edc-f54d-4ae6-a639-547717bc4d19.png)

**Comment by recrudesce** [comment]
Yeah I did, just mentioning that it's not in the documentation or the provided YAML.

**Comment by pkosiec** [comment]
Thank you @sudhanshu456 and @recrudesce for the investigation! I agree, in this line: https://github.com/infracloudio/botkube/blob/3c82d0dda688376cafd885aeca20f34ea77fb971/pkg/bot/mattermost.go#L154
probably we should also check whether the message has prefix in lowercase - so something like that:

(I believe it could be written nicely, but this is just a very fast draft)

```go
		if !strings.HasPrefix(post.Message, fmt.Sprintf("@%s ", b.BotName)) &&
			!strings.HasPrefix(post.Message, fmt.Sprintf("@%s ", strings.ToLower(b.BotName))) {
			return
		}
```

And also we should update docs for using all-in-one yaml to mention the optional bot name.

> Would it not be sensible to just standardise the case of the received name and the value read from the config file ?

I'm not sure here, because in some of the communication platforms, usernames can be case-sensitive. 

Any PR is very welcome 🙂 Thank you!

**Comment by sudhanshu456** [comment]
Cool, I will pick it up @pkosiec
